version: "3.8"

volumes:
  pgsql:
    driver: local

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - TZ=${TZ}
    ports:
      - 8090:8000
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    volumes:
      - ../lara-sample:/work
    working_dir: /work
    #command: php artisan serve --host=0.0.0.0

  db:
    build:
      context: .
      dockerfile: ./docker/pgsql/Dockerfile
      args:
        - TZ=${TZ}
    volumes:
      - ~/.lara-sample/data/postgres:/var/lib/postgresql/data
      - ./docker/pgsql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      #- TZ=Asia/Tokyo
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
      args:
        - TZ=${TZ}

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        - TZ=${TZ}
    #depends_on:
    #  - app
    ports:
      - ${NGINX_PORT:-3110}:80
    volumes:
      - ../lara-sample:/work
    env_file:
      - ./.env
