version: "3.8"

volumes:
  pgsql:
    driver: local

services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx-node/Dockerfile
      args:
        - TZ=${TZ}
    depends_on:
      - app
    ports:
      - ${WEB_PORT:-3100}:80
    volumes:
      - ../lara-sample:/work
    env_file:
      - ./.env

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - TZ=${TZ}
    #ports:
    #  - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    volumes:
      - ../lara-sample:/work
    working_dir: /work
    #command: php artisan serve --host=0.0.0.0

  db:
    build:
      context: .
      dockerfile: ./docker/pgsql/Dockerfile
      args:
        - TZ=${TZ}
    volumes:
      - ~/.lara-sample/data/postgres:/var/lib/postgresql/data
      - ./docker/pgsql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      #- TZ=Asia/Tokyo
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
      args:
        - TZ=${TZ}
