name: Discussions Notification (to private channel)

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  discussion_created:
    runs-on: ubuntu-20.04
    if: ${{ github.event.discussion && !github.event.comment }}
    steps:
      - name: Send GitHub Discussion Notification to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: author
          custom_payload: |
            {
              attachments: [{
                color: 'warning',
                text: `New Discussion by <${{ env.USER_URL }}|${{ env.USER_NAME }}>`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PRIVATE_WEBHOOK_URL }}
          DISCUSSION_URL: ${{ github.event.discussion.html_url }}
          DISCUSSION_TITLE: ${{ github.event.discussion.title }}
          DISCUSSION_BODY: ${{ github.event.discussion.body }}
          USER_URL: ${{ github.event.discussion.user.html_url }}
          USER_NAME: ${{ github.event.discussion.user.login }}

  discussion_commented:
    runs-on: ubuntu-20.04
    if: github.event.comment
    steps:
      - name: Markdown Message Adjust
        shell: bash
        run: |
          title=$(cat << "EOF"
          ${{ env.DISCUSSION_TITLE }}
          EOF
          )
          body=$(cat << "EOF"
          ${{ env.COMMENT_BODY }}
          EOF
          )
          printf -v markdown_message_unescaped %b "*<${{ env.COMMENT_URL }}|Comment on $title>*\n$body"
          echo "##[set-output name=message;]$markdown_message_unescaped"
        id: markdown_message_unescaped

      - name: Echo Markdown Message
        run: |
          echo "Message is: [${{ steps.markdown_message_unescaped.outputs.message }}]"

      - name: Send GitHub Discussions Comments to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: author
          custom_payload: |
            {
              blocks: [
                {
                  type: 'section',
                  text: {
                    type: 'mrkdwn',
                    text: `New comment by <${{ env.USER_URL }}|${{ env.USER_NAME }}>`
                  }
                }
              ],
              attachments: [
                {
                  color: 'good',
                  blocks: [
                    {
                      type: 'section',
                      text: {
                        type: "mrkdwn",
                        text: `*<${{ env.COMMENT_URL }}|Comment on ${{ env.DISCUSSION_TITLE }}>*\n`
                      }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PRIVATE_WEBHOOK_URL }}
          DISCUSSION_TITLE: ${{ github.event.discussion.title }}
          COMMENT_URL: ${{ github.event.comment.html_url }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          USER_URL: ${{ github.event.discussion.user.html_url }}
          USER_NAME: ${{ github.event.discussion.user.login }}
