name: Discussions Notification (private)
on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
jobs:
  discussion_created:
    runs-on: ubuntu-20.04
    if: ${{ github.event.discussion && !github.event.comment }}
    steps:
      - name: Send GitHub Discussion Notification to Slack
        # Note:
        # - 一度変数に入れることで、$や`をエスケープしている
        # - https://stackoverflow.com/questions/69982822/is-there-a-way-to-escape-and-single-quotes-together-in-bash
        # - printfしないといい感じに"\n"が変換されない
        run: |
          title=$(
          cat <<"EOF"
          ${{ env.DISCUSSION_TITLE }}
          EOF
          )
          body=$(
          cat <<"EOF"
          ${{ env.DISCUSSION_BODY }}
          EOF
          )
          printf -v markdown_message_unescaped %b "<${{ env.DISCUSSION_URL }}|*$title*>\n$body"
          jq -n -r --arg text "$markdown_message_unescaped" '{
            "token":"${{ secrets.SLACK_PRIVATE_BOT_TOKEN }}",
            "channel":"${{ env.CHANNEL_ID }}",
            "color":"#439FE0",
            "blocks":[
              {
                "type":"section",
                "text":{
                  "type":"mrkdwn",
                  "text":"New Discussion by <${{ env.USER_URL }}|${{ env.USER_NAME }}>"
                }
              }
              ],
              "attachments":[
                {
                  "blocks":[
                    {
                      "type":"section",
                      "text":{
                        "type":"mrkdwn",
                        "text":$text
                      }
                    }
                  ]
                }
              ]
            }' | curl -X POST
            -H 'Authorization: Bearer ${{ secrets.SLACK_PRIVATE_BOT_TOKEN }}'
            -H "Content-Type: application/json"
            -d @- https://slack.com/api/chat.postMessage
        env:
          CHANNEL_ID: ${{ secrets.SLACK_PRIVATE_CHANNEL_ID }}
          DISCUSSION_URL: ${{ github.event.discussion.html_url }}
          DISCUSSION_TITLE: ${{ github.event.discussion.title }}
          DISCUSSION_BODY: ${{ github.event.discussion.body }}
          USER_URL: ${{ github.event.discussion.user.html_url }}
          USER_NAME: ${{ github.event.discussion.user.login }}

  discussion_commented:
    runs-on: ubuntu-20.04
    if: github.event.comment
    steps:
      - name: Send GitHub Discussions Comments to Slack
        run: |
          title=$(cat << "EOF"
          ${{ env.DISCUSSION_TITLE }}
          EOF
          )
          body=$(cat << "EOF"
          ${{ env.COMMENT_BODY }}
          EOF
          )
          printf -v markdown_message_unescaped %b "*<${{ env.COMMENT_URL }}|Comment on $title>*\n$body"
          jq -n -r --arg text "$markdown_message_unescaped" '{
            "token":"${{ secrets.SLACK_PRIVATE_BOT_TOKEN }}",
            "channel":"${{ env.CHANNEL_ID }}",
            "color":"good",
            "blocks":[
              {
                "type":"section",
                "text":{
                  "type":"mrkdwn",
                  "text":"New comment by <${{ env.USER_URL }}|${{ env.USER_NAME }}>"
                }
              }
            ],
            "attachments":[
              {
                "blocks":[
                  {
                    "type":"section",
                    "text":{
                      "type":"mrkdwn",
                      "text":$text
                    }
                  }
                ]
              }
            ]
          }' | curl -X POST
          -H 'Authorization: Bearer ${{ secrets.SLACK_PRIVATE_BOT_TOKEN }}'
          -H "Content-Type: application/json"
          -d @- https://slack.com/api/chat.postMessage
        env:
          CHANNEL_ID: ${{ secrets.SLACK_PRIVATE_CHANNEL_ID }}
          DISCUSSION_TITLE: ${{ github.event.discussion.title }}
          COMMENT_URL: ${{ github.event.comment.html_url }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          USER_URL: ${{ github.event.comment.user.html_url }}
          USER_NAME: ${{ github.event.comment.user.login }}
